### ISSUE TITLE
Android Basics: Done button missing - birthday-card-app

### ISSUE THREAD

**Issue by Muhannad-issa** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#1]
**URL of codelab**
https://codelabs.developers.google.com/codelabs/basic-android-kotlin-training-birthday-card-app/#6

**In which task and step of the codelab can this issue be found?**
task: Create a Birthday Card app
step # 7

**Describe the problem**
The done button on page 7 doesn't end the section, instead it directs to the google codelabs url https://codelabs.developers.google.com/

**Steps to reproduce?**
1. Go to...  https://codelabs.developers.google.com/codelabs/basic-android-kotlin-training-birthday-card-app/#6
2. Click on... DONE button in the bottom right corner
3. See error... directs to a wrong location.

**Versions**
_Android Studio version:_  4.1
_API version of the emulator:_  29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Muhannad-issa this issue should be fixed now. Please check and update.

**Comment by ashnohe** [comment]
Issue no longer reproducible, closing issue.

Additional information:
Done button does _not_ appear if navigating to https://codelabs.developers.google.com/codelabs/basic-android-kotlin-training-birthday-card-app/#6. However, Done button does appear if accessing codelab from the associated pathway: https://developer.android.com/courses/pathways/android-basics-kotlin-three. In the latter case, the Done button now redirects us back to the correct pathway.
