### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by Mahmoud0ssama** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#100]
The site of this link https://developer.android.com/training/kotlinplayground isn't working properly

**Comment by ashnohe** [comment]
Hello @Mahmoud0ssama, thanks for reporting this issue.

The site appears to be working. May you please provide an error or a screenshot of the issue? Thanks!

**Comment by osuleymanova** [comment]
@Mahmoud0ssama 
The issue is closed as no further clarification provided.
