### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by lucky4694-github** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#104]
작업 중복 -> 중복 작업

https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#3

![image](https://user-images.githubusercontent.com/92902836/138212620-2424de7f-d806-4b75-8d53-6a44bb7f170d.png)

**Comment by osuleymanova** [comment]
Hello @lucky4694-github,

Thank you for reaching out to us. We really appreciate if you could provide the issue description in English.
