### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by IamSteelMonkey** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#105]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#3

**In which task and step of the codelab can this issue be found?**

Number 4: Print a Birthday Banner 

Step 10

**Describe the problem**

"to use the passed in" should read "to use the passed string in"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @IamSteelMonkey ,

Thank you for reaching out to us. The instruction is updated:

![Screenshot 2023-04-07 at 10 35 37 AM](https://user-images.githubusercontent.com/86437155/230652483-d559252f-44a2-41d1-8f0e-38b01b08547a.png)

All the best learning Android.
