### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by JettTexas** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#106]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
I've tried importing this code as per the android studio tutorial instructions on a new install of Android studio on windows, Mac and Linux and it fails every single time.

**Describe the problem**
Gradle fails to sync.  Interestingly with a different error each time like cannot resolve external dependency no repositories defined and task wrapper not found in project.

**Steps to reproduce?**
1. Install Android studio
2. Import birthday example code
3. See many many Gradle sync errors

**Versions**
_Android Studio version:_  newest
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment]
@JettTexas thank you for reporting this issue. The solution code has recently been updated to run on the latest version of Android Studio. If you are still experiencing this issue you might try again with the new solution code; please let us know if you're then still seeing Gradle sync errors. Thank you!

URL for context: https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app#4
