### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by buccijulio** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#109]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Lo que el curso indica que debe haceer el android studio, no lo hace

No se puede continuar

**Comment by ashnohe** [comment]
Google Translate:
Hola @buccijulio, gracias por informar de este problema. ¿Puede proporcionar una URL a la parte del laboratorio de código donde observa este problema y una descripción del problema que está encontrando? ¡Gracias!

Hi @buccijulio, thank you for reporting this issue. May you please provide a url to the portion of the codelab where you observe this issue and a description of the issue you are encountering? Thank you!

**Comment by sajibhn** [comment]
> how can I contribute to this project?
