### ISSUE TITLE
Android Basics: install-android-studio

### ISSUE THREAD

**Issue by PabloSturm** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#110]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
No es en el codelab de la instalación, sino que es en la página de descarga de Android Studio

It is not in the installation codelab, but it is in the Android Studio download page

**Describe the problem**
El problema se generá al haber seleccionado el idioma Español y tratar de descargar, no funciona el link de descarga, al elegir el idioma inglés y al hacer click en el link de descarga, se habré una nueva ventana de condiciones que hay que aceptar, que en el idioma español no aparece o no debe existir, por eso es que no se activa el link de descarga.

The problem is generated by having selected the Spanish language and trying to download, the download link does not work, when choosing the English language and clicking on the download link, there will be a new window of conditions that must be accepted, which In the Spanish language it does not appear or it should not exist, that is why the download link is not activated.

**Comment by ashnohe** [comment]
Thank you @PabloSturm for taking the time to report this issue. I've let the developer relations team know.

**Comment by ashnohe** [comment]
This issue appears to have been resolved. Let us know if that's not the case for you. Thanks!
