### ISSUE TITLE
Android Basics: install-android-studio .... I can´t to continue course

### ISSUE THREAD

**Issue by Ricardon20118** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#117]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment]
@Ricardon20118 thanks for reaching out. May you provide a description of the issue that you are seeing? Is it by chance related to #110?

**Comment by Ricardon20118** [comment]
Thanks, problem dissapear.
