### ISSUE TITLE
Android Basics: birthday-card-app -- documentation/spacing issue

### ISSUE THREAD

**Issue by dustmachine** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#12]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app#1

**In which task and step of the codelab can this issue be found?**
Step 2, under "Change the Hello World message"

**Describe the problem**
The "short hand" text is not contained within the green box describing how things could be abbreviated.

**Steps to reproduce?**
1. Go to step 2 of "Create a Birthday Card app" codelab
2. scroll down to first green box "Note"
3. Notice the abbreviation steps is outside the box and listed in the subsequent steps.

**Versions**
_Android Studio version:_ 
N/A
_API version of the emulator:_ 
N/A

**Additional information**
<img width="776" alt="Screen Shot 2020-12-26 at 6 37 24 PM" src="https://user-images.githubusercontent.com/83707/103161604-e0b5fb80-47a9-11eb-83fb-d92231e57a21.png">

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
