### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by AndresAngel2021** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#129]
Buenas noches. En el editor de playground de kotlin, no se muestra los signos ya sean de exclamación o error al lado del código, como esta indicado en 4 ITEM del curso
![Error](https://user-images.githubusercontent.com/94023217/141026384-4e7d0bc5-ac57-4d12-b524-ec19322f2b11.png)
![Item](https://user-images.githubusercontent.com/94023217/141026387-8eb9fdfc-aed6-42b9-ace9-2aaa89d86da1.png)

**Comment by osuleymanova** [comment]
@AndresAngel2021 
Thank you for reaching out to us. Entering the code in (https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS4zLjcyIiwiY29kZSI6ImZ1biBtYWluKCkge1xuICAgIHZhbCBib3JkZXIgPSBcIiVcIlxuICAgIHByaW50Qm9yZGVyKGJvcmRlcilcbiAgICBwcmludGxuKFwiSGFwcHkgQmlydGhkYXksIEpoYW5zaSFcIilcbiAgICBwcmludEJvcmRlcihib3JkZXIpXG59XG5cbmZ1biBwcmludEJvcmRlcihib3JkZXI6IFN0cmluZykge1xuICAgIHJlcGVhdCgyMykge1xuICAgICAgICBwcmludChcIj1cIilcbiAgICB9XG4gICAgcHJpbnRsbigpXG59IiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiJ9) you will get a warning message but in shared code -none(https://pl.kotl.in/S7y0dn9J4):

<img width="539" alt="Screen Shot 2022-07-29 at 5 47 07 PM" src="https://user-images.githubusercontent.com/86437155/181863914-75f21333-6a34-40d8-ba1f-4abd0af5654b.png">
