### ISSUE TITLE
Codelab UI Mobile Rendering

### ISSUE THREAD

**Issue by andobolocco** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#133]
![Screenshot_20211111-205843](https://user-images.githubusercontent.com/842842/141386717-57a10c4c-e32d-4fb3-af6e-59a7ed85dada.png)
This is how the [codelab](https://developer.android.com/codelabs/basic-android-kotlin-training-first-kotlin-program?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-kotlin-program#1)  renders for me in Chrome on an Android phone. I can zoom in but cannot zoom out, text and navigation are chopped out of the viewport.

**Comment by whallz** [comment]
Chrome version:
![Screenshot_20211111-212022](https://user-images.githubusercontent.com/842842/141387891-3c787154-181b-4c8b-b550-b322b2f1e163.png)


Android version:
![Screenshot_20211111-212054](https://user-images.githubusercontent.com/842842/141387983-be5494ee-f392-4cf9-9841-d9ba1a4e48d0.png)
