### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by aruntracer** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#14]
**https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#2**

**3. Run your app on a virtual device (emulator)**

**When I run the AVD, it throws "Could not identify launch activity: Default Activity not found", there is no step in the codelabs to create a activity under happybirthday package, but in codelab it says after launching your AVD it will display HelloWorld message **

**Steps to reproduce?**
1. https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#2
2. Follow the steps in the above link
3. You will get "Could not identify launch activity: Default Activity not found" error after launch AVD.

**Versions**
_Android Studio version:_ 4.1.1
_API version of the emulator:_ Pixel 4 XL API 
![error](https://user-images.githubusercontent.com/5306750/104598572-bc5c8900-569c-11eb-976f-e4e773cd1fa1.jpg)
30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@aruntracer 
We appreciate you bringing this issue to our attention.
We changed the folder structure, so this should be resolved. Download the code again and try.
PR   https://github.com/google-developer-training/android-basics-kotlin-birthday-card-app-solution/pull/15
