### ISSUE TITLE
https://developer.android.com/training/kotlinplayground?hl=es

### ISSUE THREAD

**Issue by rlanfri** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#150]
![Captura de Pantalla 2021-11-13 a la(s) 13 10 28](https://user-images.githubusercontent.com/49770658/141650869-3624bf3c-15e4-4314-aa31-7ba47b0d90d2.png)
Hello! I need help! I am new to programming and this problem does not allow me to visualize the result of my code.
Is it a problem related to my browser? to java? Hopefully you can help me.
Thank you

**Comment by osuleymanova** [comment]
@rlanfri 
Our apologies for the late reply. Could you provide the url of the codelab and the code snippet so we may help with troubleshooting?

**Comment by osuleymanova** [comment]
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
