### ISSUE TITLE
Android Basics: install-android-studio

### ISSUE THREAD

**Issue by ericoporto** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#16]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-install-android-studio?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-install-android-studio#2

**In which task and step of the codelab can this issue be found?**
3. Verify system requirements

**Describe the problem**

It doesn't describe or at least mentions that Android Studio is supported in Linux. I did the course using Ubuntu 20.04 and it was all fine.

**Comment by brendonenoe** [comment]
Can someone help me install my android studio ...I dont know where I'm going wrong![IMG_20210121_174917_5.jpg](https://user-images.githubusercontent.com/77880851/105606082-ebab7e00-5d9f-11eb-8500-6d93d7ded955.jpg)![IMG_20210121_174955_9.jpg](https://user-images.githubusercontent.com/77880851/105606086-f36b2280-5d9f-11eb-9442-ad4a0d2f7390.jpg)

**Comment by jtavva** [comment]
@ericoporto 
Thank you for reaching out to us. 
The course instructions are mostly geared towards the most commonly used OS. 
Thank you for letting us know that you were able to do the course in Ubuntu.

**Comment by jtavva** [comment]
@brendonenoe 
Thank you for reaching out to us.
I am sorry you are having problems installing Android Studio.
Could you please uninstall Android Studio and install it using the following guide.
https://developer.android.com/studio/install
