### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by DiddiLeija** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#163]
Hi, I was taking the codelab of this activity on [this course](https://developer.android.com/courses/pathways/android-basics-kotlin-one) when I noticed a badly formatted text:

![image](https://user-images.githubusercontent.com/83621221/141842520-04bdafa7-9159-468d-a49b-5435f1c14714.png)

I expected that the "code" were text and the "text" shown here were inside the code block. Actually, this is not a showstopper for the course, but it would be better if it were formatted correctly. I found similar mistakes around the codelab.

For example, I found "normal text" formatted as code (`like this text`).

----

Please tell me if this is a normal behavior, or unrelated to this repo :smile:.

**Comment by osuleymanova** [comment]
@DiddiLeija 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-08-01 at 4 03 18 PM](https://user-images.githubusercontent.com/86437155/182259731-3a153a7c-95ce-4694-862d-b74e9a476ed0.png)

**Comment by DiddiLeija** [comment]
Thank you @osuleymanova!
