### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by chrissmith10** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#17]
I'm not sure what anything below is. This whole reporting a problem on github seems odd to me, but anyways... Under section "3 Run your app on a virtual device (emulator)" it says to go to tools >> AVD Manager. AVD Manager is now in icon between Sync Project with Gradle Files and SDK Manager.

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@chrissmith10 
Thank you for reaching out to us.
You can launch the **AVD manager** using the icon in the toolbar and also using the menu option. 
They both do the same thing, launching AVD manager via menu option, **Tools > AVD** Manager is still a valid option.
