### ISSUE TITLE
Android Basics issue: Typo 

### ISSUE THREAD

**Issue by AmeyaJain-25** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#170]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#3

**In which task and step of the codelab can this issue be found?**
In the "Create a birthday message in Kotlin" codelab, the 4th section of "print a birthday banner with border"

**Describe the problem**
In the "Create a birthday message in Kotlin" codelab, the 4th section of "print a birthday banner with border" is having a typo in 8th point of **Use arguments to change the border** section.

It is written as,
_In the editor, notice a grayed exclamation mark. This icon indicates a warning. Warnings are about issues with your code that you need to pay attention to, but they don't **keep** your code from running_

But it should be,
_In the editor, notice a grayed exclamation mark. This icon indicates a warning. Warnings are about issues with your code that you need to pay attention to, but they don't **stop** your code from running_

**Steps to reproduce?**
1. Go to the codelab of "Create a birthday message in Kotlin"
2. Click on 4th section of "Print the birthday banner with a border"
3. See the 8th point under "Use arguments to change the border"

**Additional information**
![image](https://user-images.githubusercontent.com/66305085/143610949-23d6796a-76da-4a45-93d3-1a2114bcbd10.png)

**Comment by osuleymanova** [comment]
Hello @AmeyaJain-25,

Thank you for reaching out to us. Your suggestion was accepted:


![Screenshot 2023-04-03 at 2 04 50 PM](https://user-images.githubusercontent.com/86437155/229627694-06ac3d37-27a4-48dc-adcd-7da0ae24d0a1.png)
