### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by chrissmith10** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#18]
One more issue that I'm having on that same section is this android emulator with an amd processor. It's actually not mentioned in this tutorial, but messing around with Kotlin a bit it keeps coming up. Are there any other instructions to follow than the instructions at https://github.com/google/android-emulator-hypervisor-driver-for-amd-processors ?? I didn't find them helpful. Thank you!

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@chrissmith10 
Thank you for reaching out to us.
**"Android Emulator Hypervisor Driver for AMD Processors"** is beyond the scope of this course.
