### ISSUE TITLE
Android Basics: run-on-mobile-device

### ISSUE THREAD

**Issue by chrissmith10** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#19]
In section "2. Turn on USB debugging" I do not have "Build number" in About and I don't see "System" in Settings either. I have a Samsung Galaxy J3 Mission

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@chrissmith10 
Thank you for reaching out to us.
Please refer to the [Galaxy J3 Mission user manual](https://ss7.vzw.com/is/content/VerizonWireless/Devices/Samsung/galaxy-j3-mission/samsung-j3-mission-ug.pdf), on page number 166 you should find the instructions on how to view the Build Number.

**Comment by ashnohe** [comment]
Closing issue for now, please reach out if you are still having trouble locating the build number. Thanks!
