### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by vijdroid** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#192]
Hello Google,
I have find some bug regarding UI.
Website is not responsive can't read content.
I have attached snap please have look.

![Screenshot_20211222-202732](https://user-images.githubusercontent.com/71219144/147112362-ea312be4-98b5-4dc0-a836-5fdf703db47a.png)

**Comment by blackcrown01** [comment]
have you tried to use PC mode on the browser ?
try it with lanscape rotation it may fix it for you .
