### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by ARJUN-SREEKUMAR** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#206]
The sign-in button in developers.android website is not working

**Comment by osuleymanova** [comment]
@ARJUN-SREEKUMAR #
Please provide the required details while reporting an issue so that we can help you with troubleshooting.

**Comment by osuleymanova** [comment]
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
