### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by andres-cm90** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#22]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app#4

**In which task and step of the codelab can this issue be found?**
5

**Describe the problem**
Talks about how to import a new project, without accounting for all the prompt the user gets and what to do. It asks initially to either "Create project from existing sources" or "Import project from external model", for which a new user like me would have no idea what to pick. I left it as it was, but apparently I was mistaken and should've been "Import project from external model"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version: 4.1.2
__API version of the emulator:_ 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@andres-cm90 
Please select "Import project", it is mentioned in the instructions. 
![image](https://user-images.githubusercontent.com/24260141/113641931-75df5080-9633-11eb-8734-a5f5819916ed.png)
