### ISSUE TITLE
Android Basics issue: Code doesn't run

### ISSUE THREAD

**Issue by isaacbird8** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#227]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#3)**

**In which task and step of the codelab can this issue be found? Task 4: Print a birthday banner with a border: use arguments to change the border steps 5-7**

**Describe the problem. I have used the right code, but it doesn't run. I copied the example code and pasted in the kotlin playground but it still does not run, shows errors.**

**Steps to reproduce?**
1. Go to lesson mentioned above
2. Copy code example and paste in kotlin playground
3. See error Expecting property name or receiver type
Unresolved reference: border
Unresolved reference: border

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._ 
![image](https://user-images.githubusercontent.com/100881453/156664749-1bf8b543-8b2d-4fa2-9865-1e24dd07c5a4.png)

**Comment by AcrowsShadow** [comment]
I hope that you were able to get past this but I can see where you may have a issue. It's with your with val, you aren't giving it the border name and so everywhere you are inputting border it isn't seeing the val border = "%".

**Comment by isaacbird8** [comment]
Yes, I eventually realized my mistake and was able to correct it. Thank you very much
