### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by Alirezaqp** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#23]
in (part 4) ,the final codes have an issue
past that and u will see

**Comment by jtavva** [comment]
@jtavva 
Could you please give us more more information to further debug the issue. 

**URL of codelab**


**In which task and step of the codelab can this issue be found?**


**Describe the problem**


**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 


**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment]
I'm not able to replicate an issue with part 4 and am therefore closing this issue for now. Feel free to provide more information if you are still experiencing an issue. Thanks!
