### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by xpyramiid** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#241]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
This is shown as example of "entire program"

fun main() {
    printBorder()
    println("Happy Birthday, Jhansi!")
    printBorder()
}

fun printBorder() {
    repeat(23) {
        print("=")
    }
    println()
}

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot (1)](https://user-images.githubusercontent.com/87555566/163514381-f9e55c6d-f702-4f19-8154-5f333cc3d779.png)

**Comment by xpyramiid** [comment]
This looks like the spot.

![Screenshot (3)](https://user-images.githubusercontent.com/87555566/163516131-bf8bf575-0fa7-43e7-b8f9-f7299b5cdfd3.png)

I think more like this would work.

![Screenshot (4)](https://user-images.githubusercontent.com/87555566/163516310-cd6f0b68-40bf-48b0-be95-832180fc85e6.png)

**Comment by osuleymanova** [comment]
@xpyramiid 
Thank you for reaching out to us. The code and the output provided in the codelab are correct. Could you please be more specific with the issue?
