### ISSUE TITLE
Android Basics issue: kotlin playground will not run the program

### ISSUE THREAD

**Issue by pandora45** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#247]
https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#

Pt. 5: The issue is completing the taske to create a birthday message

**Describe the problem**
The problem is with the kotlin playground it will not run the program or even provide an error message

**Steps to reproduce?**
1. Go to...kotlin playground
2. Click on...input a simple code
3. See error... there is no output code solutions or otherwise

**Versions**
_Android Studio version:_  web based simulator
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@pandora45 
Thank you for reaching out to us. Could you please provide the code snippet so we may help with troubleshooting?

**Comment by osuleymanova** [comment]
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
