### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by angelair1465** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#249]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#0)

5

The codelab instructions and the solution code do not match

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@angelair1465 
Could you be more specific with examples please?

**Comment by osuleymanova** [comment]
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
