### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by Barry56** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#25]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/79868740/109542963-aaed0600-7abd-11eb-8c3c-dbbdec8b3ab1.png)
![Warnings in component tree](https://user-images.githubusercontent.com/79868740/109543098-d53ec380-7abd-11eb-91bb-471e7009dc91.JPG)
When I run the app the two text views don't appear in the emulator... 
I ran the suggested 'fix' and the I got this 
![Error code](https://user-images.githubusercontent.com/79868740/109543472-39fa1e00-7abe-11eb-8f64-f264cba3f6a1.JPG)

Any advice would be welcomed :) :)

**Comment by jtavva** [comment]
@Barry56 
Thank you for reaching out to us. 
Please provide us with the XML code of `activity_main.xml`

**Comment by ashnohe** [comment]
Closing issue for now, but feel free to provide the XML code or check out the solution as described here: https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app#4
