### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by hrishikeshp20** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#251]
**URL of [codelab](https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app#2)**

**In which task and step of the codelab can this issue be found?**Step 3(add text view to layout) in Create  a Birthday Card app

**Describe the problem** Just a spelling mistake ConstrainLayout

**Steps to reproduce?**
1. Go to... Position the TextView heading
2. Click on... Under that  check the last word of point no.3
3. See error... It is ConstrainLayout, should be ConstraintLayout

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/88403078/169194617-799fe625-4dac-42ca-8a9b-e04bb53f4d8d.png)

**Comment by osuleymanova** [comment]
@hrishikeshp20 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-07-29 at 2 22 10 PM](https://user-images.githubusercontent.com/86437155/181844871-260badcd-f29d-47d1-92e7-4dab9b4147aa.png)
