### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by Qlander17** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#256]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#2

**In which task and step of the codelab can this issue be found?**

Step 3 " Run your app on a virtual device (emulator)". *Last task for step 3*

**Describe the problem**

Virtual device will not power on or launch. The name I've given to the virtual device is: Ghost Protocol.

After creating the virtual device, I launch or run the device/app, the emulator opens and the virtual device is displayed. However, it does not power on. It is stuck on the Google "G" emblem and displays a progress bar that never finishes. The display never changes to what is shown in the codelab: with the title of "Happy Birthday" and the message "Hello World" showing on the screen. Clicking on the Home or Back options does nothing...

Android Studio displays the following errors:

12:10 PM	Adb connection Error:An existing connection was forcibly closed by the remote host

12:10 PM	Cannot reach ADB server, attempting to reconnect.

12:10 PM	* daemon not running; starting now at tcp:5037

12:10 PM	* daemon started successfully

12:10 PM	Unable to open connection to ADB server: java.io.IOException: Can't find adb server on port 5037, IPv4 attempt: Connection refused: connect, IPv6 attempt: Connection refused: connect

12:10 PM	Failed to start monitoring emulator-5554

AND....
 
05/24 12:08:55: Launching 'app' on Ghost Protocol.
Error while waiting for device: AVD Ghost_Protocol is already running.
If that is not the case, delete the files at
   C:\Users\Ghost Protocol\.android\avd/Ghost_Protocol.avd/*.lock
and try again.

There is NO *.lock file located in the Ghost_Protocol.avd directory...

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 11.0.12+7-b1504.28-7817840 amd64
_API version of the emulator:_  31

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot (9)](https://user-images.githubusercontent.com/105952164/170087060-6e19f87b-d7a6-4128-b133-82844f85d439.png)

**Comment by rishav2220** [comment]
U can try " Settings - Build, Execution.... - Debugger - untick "Enable adb mDNS for wireless debugging"..

**Comment by rishav2220** [comment]
> **URL of codelab**
> 
> https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#2
> 
> **In which task and step of the codelab can this issue be found?**
> 
> Step 3 " Run your app on a virtual device (emulator)". _Last task for step 3_
> 
> **Describe the problem**
> 
> Virtual device will not power on or launch. The name I've given to the virtual device is: Ghost Protocol.
> 
> After creating the virtual device, I launch or run the device/app, the emulator opens and the virtual device is displayed. However, it does not power on. It is stuck on the Google "G" emblem and displays a progress bar that never finishes. The display never changes to what is shown in the codelab: with the title of "Happy Birthday" and the message "Hello World" showing on the screen. Clicking on the Home or Back options does nothing...
> 
> Android Studio displays the following errors:
> 
> 12:10 PM Adb connection Error:An existing connection was forcibly closed by the remote host
> 
> 12:10 PM Cannot reach ADB server, attempting to reconnect.
> 
> 12:10 PM * daemon not running; starting now at tcp:5037
> 
> 12:10 PM * daemon started successfully
> 
> 12:10 PM Unable to open connection to ADB server: java.io.IOException: Can't find adb server on port 5037, IPv4 attempt: Connection refused: connect, IPv6 attempt: Connection refused: connect
> 
> 12:10 PM Failed to start monitoring emulator-5554
> 
> AND....
> 
> 05/24 12:08:55: Launching 'app' on Ghost Protocol. Error while waiting for device: AVD Ghost_Protocol is already running. If that is not the case, delete the files at C:\Users\Ghost Protocol.android\avd/Ghost_Protocol.avd/*.lock and try again.
> 
> There is NO *.lock file located in the Ghost_Protocol.avd directory...
> 
> **Steps to reproduce?**
> 
> 1. Go to...
> 2. Click on...
> 3. See error...
> 
> **Versions** _Android Studio version:_ 11.0.12+7-b1504.28-7817840 amd64 _API version of the emulator:_ 31
> 
> **Additional information** _Include screenshots if they would be useful in clarifying the problem._ ![Screenshot (9)](https://user-images.githubusercontent.com/105952164/170087060-6e19f87b-d7a6-4128-b133-82844f85d439.png)

U can try " Settings - Build, Execution.... - Debugger - untick "Enable adb mDNS for wireless debugging"..

**Comment by rishavshrivas** [comment]
@Qlander17 U can try " Settings - Build, Execution.... - Debugger - untick "Enable adb mDNS for wireless debugging"..
