### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by kdh78r** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#258]
It would be nice if you actually showed where the layout editor actually is. I am not seeing this in the "ide."
Android Studio is, by far, the worst "ide" I have had the displeasure of using in my life. Those that created it should be embarrassed and stop "developing" software. I have seen better projects from middle school students. The Resource manager is perpetually saying "waiting for the build to finish" for the last hour.

**Comment by rishavshrivas** [comment]
it is in "src/main/res/layout/activity_main.xml"

> It would be nice if you actually showed where the layout editor actually is. I am not seeing this in the "ide."
> Android Studio is, by far, the worst "ide" I have had the displeasure of using in my life. Those that created it should be embarrassed and stop "developing" software. I have seen better projects from middle school students. The Resource manager is perpetually saying "waiting for the build to finish" for the last hour.

it is in "src/main/res/layout/activity_main.xml"
