### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by GM456742** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#263]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
The statement for step 8...
`In the editor, notice a grayed exclamation mark. This icon indicates a warning. Warnings are about issues with your code that you need to pay attention to, but they don't keep your code from running.`

...appears to be an incorrect statement .The last end of the statement should read ...**but they don't keep your code from not running.**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@GM456742 
Thank you for reaching out to us. Please provide the codelab URL.

**Comment by osuleymanova** [comment]
Hello @GM456742,

My apologies for the late response. 
We have reviewed the statement and made some edits to it.
Please tale a look at the screenshot below:

![Screenshot 2023-04-07 at 10 44 34 AM](https://user-images.githubusercontent.com/86437155/230654037-5c2435db-259f-4806-92d5-48c9425ed1af.png)
