### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by mutazx1** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#266]
i cant find the common attributes

**Comment by osuleymanova** [comment]
@mutazx1 
Thank you for reaching out to us. While reporting an issue please provide the required details (codelab url at least) so we could navigate you with troubleshooting.

**Comment by osuleymanova** [comment]
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
