### ISSUE TITLE
Android Basics issue:The kotlin code is missing the line break.The code runs correctly but is not as the output should be.

### ISSUE THREAD

**Issue by bilalmohib** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#267]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#3

**In which task and step of the codelab can this issue be found?**
I have attached the screenshot.A line break is missing here in the code.

**Describe the problem**
A line break in the following code is missing whos output is this
```bash
=======================
Happy Birthday, Jhansi!
=======================
```

The code that is missing line break is this.
At heading Repeat a border pattern
```kotlin
fun main() {
    printBorder()
    println("Happy Birthday, Jhansi!")
    printBorder()
}

fun printBorder() {
    repeat(23) {
        print("=")
    }
    println()
}
```

The code must be this to achieve the given output
```kotlin
fun main() {
    printBorder()
    println("\nHappy Birthday, Jhansi!")
    printBorder()
}

fun printBorder() {
    repeat(23) {
        print("=")
    }
}
```
as shown below in the image its missing the line break \n in the print statement.
![Screenshot (617)](https://user-images.githubusercontent.com/59303181/175309983-7c17e500-6153-43d1-8742-10eb6c8ff2f8.png)

**Steps to reproduce?**
1. Go to Heading Repeat a border pattern
2. Use the code given in the codelab
```kotlin
fun main() {
    printBorder()
    println("Happy Birthday, Jhansi!")
    printBorder()
}

fun printBorder() {
    repeat(23) {
        print("=")
    }
    println()
}
```
4. See error the output is this
```bash
=======================Happy Birthday, Jhansi!
=======================
```
while output shown uses line break

**Versions**
_Android Studio version: All
_API version of the emulator: All

**Additional information**
I have attached the screenshot here 
![Screenshot (616)](https://user-images.githubusercontent.com/59303181/175309724-414792f4-342a-4990-89de-93a518a9b711.png)
Here its more clearer
![Screenshot (617)](https://user-images.githubusercontent.com/59303181/175309916-1f6ed65e-7cad-4376-8538-928f588b4a88.png)

**Comment by osuleymanova** [comment]
@Muhammad-Bilal-7896 
Thank you for reaching out to us. The code and the output provided in the codelab are correct. Please review the screenshot below:

![Screen Shot 2022-08-01 at 11 30 51 AM](https://user-images.githubusercontent.com/86437155/182219675-41f5df56-6a58-48f7-87da-e13ff4f10667.png)
