### ISSUE TITLE
Android Basics: birthday-card-app - Can't see Common Attributes, and forced to set attributes manually

### ISSUE THREAD

**Issue by francescobau** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#268]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app

**In which task and step of the codelab can this issue be found?**
Task 4 : Add style to the text
Step 2+ : "Notice the various attributes including fontFamily, textSize, and textColor." onwards

**Describe the problem**
I followed all the instructions step-by-step, but it doesn't show "Common Attributes" and in "All Attributes" the attribute "textAppearance" does not have other features, unlike the ones shown in the example (e.g. "fontFamily" is a separated attribute, there is NO textSize, and there is NO textColor.

**Steps to reproduce?**
1. Go to the Component Tree
2. Click on the TextView inside the ConstraintLayout
3. Go to "All Attributes" ("Common Attributes" is not available, even if they are set to be visible in that section
4. Search "textSize" or "textColor"
5. The attributes are not available.

**Versions**
_Android Studio version:_  Android Studio Bumblebee | 2021.1.1 Patch 3
_API version of the emulator:_ 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![immagine](https://user-images.githubusercontent.com/56580849/175618607-77004781-0ecf-4424-ba32-3e1f57794f14.png)

![immagine](https://user-images.githubusercontent.com/56580849/175618640-5384c2d7-3f18-4e35-8160-d484b87fb8a0.png)

![immagine](https://user-images.githubusercontent.com/56580849/175618682-a5a3337f-86d7-49da-8e3e-aa282eb1caff.png)

**Comment by sawyerhamann** [comment]
Same problem, but I don't even know how to set the attributes manually.
