### ISSUE TITLE
Android Basics: run-on-mobile-device

### ISSUE THREAD

**Issue by NaplesDave** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#269]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Step 3 Item 3.

**Describe the problem**
States to select Google USB Driver from list.
I am using CHIPMUNK , 2021.2.1 Patch 1
There is NO "Google USB Driver " shown in my listing?

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Chipmunk 2021.2.1 Patch 1
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@NaplesDave 
Please provide the URL of the codelab.

**Comment by osuleymanova** [comment]
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
