### ISSUE TITLE
Android Basics: install-android-studio

### ISSUE THREAD

**Issue by Kalabaza** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#27]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-install-android-studio?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-install-android-studio#4

**In which task and step of the codelab can this issue be found?**
5

**Describe the problem**
The welcome image for the Windows installation instructions is actually the macOS image.

**Steps to reproduce?**
1. Go to "Download and install Android Studio" codelab
2. Scroll to the bottom of the page
3. See wrong image being displayed

**Versions**
_Android Studio version:_ N/A

_API version of the emulator:_ N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![2021-03-16 14_49_10-Window](https://user-images.githubusercontent.com/3315148/111320063-e7e0fd00-8666-11eb-8936-0a58e10fc2ad.png)

**Comment by osuleymanova** [comment]
@Kalabaza 
Thank you for reaching out to us. The content was updated and it will be published soon.
