### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by JudeIsong** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#272]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#2

**In which task and step of the codelab can this issue be found?**
The task where I launched the emulator

**Describe the problem**
after running the app on an emulator on my android studio. It displayed "system UI isn't responding" and I click wait but the emulator did not display the app as it should!

**Steps to reproduce?**
1. Go to...device manager in Android Studio, select the pixel 5 API 31
2. Click on... Run
3. See error... the Emulator didn't displayed the result of the app as expected

**Versions**
_Android Studio version:_ Android Studio 12.0 Google APIs | x86_64

_API version of the emulator:_ 31

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Capture](https://user-images.githubusercontent.com/62698057/180182837-dffa7e24-1d3b-4e12-991d-22e3b15c7aff.PNG)
![Capture](https://user-images.githubusercontent.com/62698057/180182929-e4525608-9645-4ade-a8d3-94d194618cb6.PNG)

**Comment by JudeIsong** [comment]
It is now working guys...Thank you.

**Comment by osuleymanova** [comment]
@JudeIsong 
Thank you for reaching out to us and informing that no more issue observed.
