### ISSUE TITLE
Android Basics instructions issue:

### ISSUE THREAD

**Issue by tonymena84** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#273]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#4

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
instruction not coming across when read.  issue understanding instructions.
not enough explanation before transitioning to instructions 3 and 4.

it took to long figuring out my mistake,  . I wasn't  designating what symbol i wanted printed for my  cake top. 
ref. Print ("=") 
I didn't intuitively realize i was designating what i wanted printed, despite what i previously learned. i have zero previous experience with  coding.
please add  explanation  reiterating what i am actually doing to help bridge the gap.

instruction:
Create printCakeTop()
The printCakeTop() function to print the top of the cake, a line of equal signs, is almost the same as the printBorder() function you created earlier in this codelab.

==========================

1. Below the main() function, add a blank line, and then create a function, printCakeTop() that takes one argument, age, of type Int.
2. Inside, use a repeat() statement to print one equal sign age times plus 2. The extra two equals signs are so that the candles won't fall off the side of the cake.
3. At the end, when the repeat() is done, print an empty line.
4. In main(), remove the two // symbols from the beginning of the line of code for printCakeTop(), because the function now exists.

printCakeTop(age)
Here is your finished function.

fun printCakeTop(age: Int) {
    repeat(age + 2) {
        print("=")
    }
    println()
}
Run your code to see the top of the cake.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![as instructed](https://user-images.githubusercontent.com/110062404/181112591-dc8751bd-53cc-4db7-b23d-eceb661efe53.jpg)

**Comment by osuleymanova** [comment]
@tonymena84 
Thank you for reaching out to us. The code provided in the codelab is correct. Following the steps in the codelab there should be no errors or warnings. Please see the the correct code in the screenshot below:

![Screen Shot 2022-08-25 at 1 12 17 PM](https://user-images.githubusercontent.com/86437155/186759883-01cd65eb-df22-41cb-9116-e2998b74732e.png)
