### ISSUE TITLE
Kotlin Playground issue: No warning icons

### ISSUE THREAD

**Issue by loothunter1** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#274]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message#3)

**In which task and step of the codelab can this issue be found?**

https://developer.android.com/training/kotlinplayground
A grayed exclamation mark (warning about parameter never used) doesn't show.

**Steps to reproduce?**
1. Make a code with unused parameter. For example:
`
fun main() {
    val border = "%"
    printBorder(border)
    println("Happy Birthday, Jhansi!")
    printBorder(border)
}

fun printBorder(border: String) {
    repeat(23) {
        print("=")
    }
    println()
}
`
2. "Warning" mark doesn't show the way "Birthday message" excercise describes.
3. Probably it has to do with https://try.kotlinlang.org/static/images/icons_all_sprite.svg file absent

**Versions**
The problem is with the site.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@loothunter1 
Please provide the URL of the codelab.

**Comment by loothunter1** [comment]
> @loothunter1 Please provide the URL of the codelab.

You mean URL of the excercise? Haven't I already? (at the very top) https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message#3
