### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by hemm56** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#29]
fun main() {
    val age = 24
    val layers = 5
    // printCandles(age)
    // printCakeTop(age)
    // printCakeBottom(age, layers)

when i make a run for this code the progrqaam giving me this comment
 i am write the code correct

**Comment by osuleymanova** [comment]
@hemm56 
Thank you for reaching out to us. Your code is correct , just add  } at the end.
