### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by Jacobs4** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#3]
Can you include more features about kotlin program (more about IDE solutions) for more compatible for user

**Comment by jtavva** [comment]
@Jacobs4 This is just introduction course for Kotlin. You will more on how to use Kotlin in Android programing in Android Studio in later pathways. 
We have [Kotlin Bootcamp for Programmers](https://developer.android.com/courses/kotlin-bootcamp/overview) if you want learn further.
