### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by klharless** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#31]
**URL of codelab**

https://github.com/google-developer-training/android-basics-kotlin-birthday-card-app-solution/issues/new?template=android-basics-issue.md&title=Android%20Basics%3A%20birthday-card-app

**In which task and step of the codelab can this issue be found?**
Add style to the text

**Describe the problem**

3.  Step Look for textAppearance.
4. If textAppearance is not expanded, click on the down triangle.
Should be

3.  Look for textSize.
4.  If textSizeis not expanded, click on the down triangle.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment]
Step 6 in the description now reads, "Set the textSize to 36sp" instead of "If textSizeis not expanded, click on the down triangle."
