### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by CuzImBisonratte** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#326]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#1

**In which task and step of the codelab can this issue be found?**
`2. Create your first app` > `Create an Empty Activity project` > Step 11 AND 12

**Describe the problem**
1. The tutorial says the user should select Kotlin as the language.
        The Selection is not availible in Android Studio
2. The tutorial says the user should select `API 19: Android 4.4 (KitKat)`.
        The minimum SKD-Version in Android Studio is `API 21: Android 5.0 (Lollipop)`!

**Versions**
_Android Studio version:_ Android Studio Flamingo | 2022.2.1 Patch 1 (built on April 19, 2023)

**Additional information**
![grafik](https://user-images.githubusercontent.com/50182241/236830859-e93b11ff-8b85-4db4-889b-3e335e2fcf18.png)
![grafik](https://user-images.githubusercontent.com/50182241/236831017-45e46d67-999a-4aed-80c3-4d126e36f5ad.png)

**Comment by JayMad18** [comment]
Google no longer supports KitKat from what I can see on google, have you tried selecting kotlin for a different SDK such as lollipop?
