### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by Rozenwaard** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#329]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app#1

**In which task and step of the codelab can this issue be found?**
From the beginning

**Describe the problem**
There's no such presets in current Android Studio version

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Rozenwaard** [comment]
Android Studio Flamingo | 2022.2.1 Patch 1

**Comment by raphaeluziel** [comment]
Choose "Empty Views Activity" instead of the "Empty Activity" that they say.  A lot of the debugging also seems very different.
