### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by PalGria** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#35]
`https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?authuser=3&hl=es&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%3Fhl%3Des%26authuser%3D3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#2`

Task 3 step 2

There's a photo out of place.

![Captura](https://user-images.githubusercontent.com/8961037/112859270-f261b480-90b2-11eb-9580-cba542020728.PNG)

**Comment by osuleymanova** [comment]
@PalGria 
Thank you for reaching out to us and reporting this overlapping issue. It was fixed:

![Screen Shot 2022-08-02 at 1 59 09 PM](https://user-images.githubusercontent.com/86437155/182472420-e62f756f-47d6-46c5-8f60-b61faaea7ea1.png)
