### ISSUE TITLE
Android Basics: install-android-studio

### ISSUE THREAD

**Issue by OmdevShastri** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#36]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-install-android-studio#5

**In which task and step of the codelab can this issue be found?**

The ending part
**Describe the problem**
No next button

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@OmdevShastri 
The ticket is closed as wontfix as Next button is missed intentionally.
