### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by elyasaf755** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#38]
The line "Note that changing to code to make it better or easier to work with without changing the output is called "refactoring"." should be "Note that changing *the* code to make it better or easier to work with without changing the output is called "refactoring"." instead.

**Comment by osuleymanova** [comment]
@elyasaf755 
Thank you for reaching out to us. The issue is fixed.
