### ISSUE TITLE
Wrong Template is suggested in Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by dchelnokov** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#382]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app
additionally described by a Stackexchange user named dragun here: https://stackoverflow.com/questions/76095138/no-layout-folder-in-androidstudio

**In which task and step of the codelab can this issue be found?**

In the Step 2: "Setup your Happy Birthday App"

**Describe the problem**

It is suggested to use  an "**Empty Activity projec**t" and expected that the user will have access to _/app/res/layout/activity_main.xml_, while it doesn't work so in the version of Android Studio Giraffe 2022.3.1 Patch 2 (built on Sep 14, 2023). Instead the user needs to choose the "**Empty Views Activity**" at the time of creating the project.

In my situation the "Empty Activity" doesn't contain the Android version 4 in the selection list, while the Empty View Activity does.

**Steps to reproduce?**
0. Download and installl the Android Studio Giraffe | 2022.3.1 Patch 2 Build #AI-223.8836.35.2231.10811636, built on September 14, 2023 under Ubuntu 23.04 Lunar
1. Go to Step 2  and follow the instructions till the part "Change the Hello World message"
2. Click on the "res" folder in the project to see that there is no layout folder under res, unless "Empty View Activity" was selected at creation.
3. See error: there is no layout folder.

**Versions**
_Android Studio version:_ Android Studio Giraffe | 2022.3.1 Patch 2
_API version of the emulator:_ could not find it 

**Additional information**
Possible solution is to change the wording from "Empty Activity" to "Empty View Activity" in the Codelab.
_Include screenshots if they would be useful in clarifying the problem._
https://i.stack.imgur.com/k1AL9.png
![no_layout_folder](https://github.com/google-developer-training/android-basics-kotlin-birthday-card-app-solution/assets/19837826/f42123d2-894e-4942-b64d-cd182c02962c)

Thanks!

**Comment by jlulovics** [comment]
Thank you for your feedback. This content has been deprecated. Please visit https://developer.android.com/courses/android-basics-compose/course for the latest recommended best practices for Android development.
