### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by baedole2** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#383]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three&hl=ko#1

**In which task and step of the codelab can this issue be found?**
2. Set up your Happy Birthday app

**Describe the problem**

The layout folder and its sub XML files are missing. Currently, Android Studio is not configured based on the described template. Progress is not pos
--------------------------
It has been confirmed that in the latest version of Android Studio, the project should be run as an Empty Views Activity instead of an Empty Activity to proceed with the work.

**Comment by jlulovics** [comment]
Thank you for your feedback. This content has been deprecated. Please visit https://developer.android.com/courses/android-basics-compose/course for the latest recommended best practices for Android development.
