### ISSUE TITLE
Android Basics: install-android-studio

### ISSUE THREAD

**Issue by soydepr** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#39]
* avd manager not showing up 
* 
![Screenshot 2021-04-06 5 29 33 PM](https://user-images.githubusercontent.com/546367/113780970-f66a8380-96fd-11eb-8263-36ebab76236e.png)

**Comment by ashnohe** [comment]
@soydepr Thank you for reaching out. May you please ensure that your computer meets the requirements for running apps on an emulator (see [Requirements and recommendations](https://developer.android.com/studio/run/emulator#requirements)) and that the AVD Manager is [installed](https://developer.android.com/studio/run/emulator#install)?
