### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by ArshanKhanifar** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#4]
**URL of codelab**
https://codelabs.developers.google.com/codelabs/basic-android-kotlin-training-birthday-card-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fcodelabs.developers.google.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app#4

**In which task and step of the codelab can this issue be found?**
It was in step 5 of the `Create a Birthday Card app` 

**Describe the problem**

I cloned the project and opened android studio and opened the project folder in android studio. Android studio didn't detect the project and the Run button is greyed out. 

**Steps to reproduce?**
1. Clone the repository: 
```
git clone  https://github.com/google-developer-training/android-basics-kotlin-birthday-card-app-solution
```
2. Open the project in android studio

3. Project doesn't get detected and the run button is greyed out. 

**Versions**
_Android Studio version:_  

Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: IdeaVIM, com.thoughtworks.gauge, org.intellij.plugins.markdown

_API version of the emulator:_  didn't use emulator. I've been using my Google Pixel 4a. 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![screenshot](https://user-images.githubusercontent.com/10492324/98446078-43afde00-20e9-11eb-8284-f38e89dd2820.png)

**Comment by jtavva** [comment]
@ArshanKhanifar 
Thank you reporting this.
Make sure that you're opening the sub-directory, **HappyBirthday** in Android Studio and not the parent directory.
We added a similar note in the codelab and will be published soon.
