### ISSUE TITLE
Needed a proper walk through of how to run the imported project from github in android studio 

### ISSUE THREAD

**Issue by pandashashwat97** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#42]

**Comment by ashnohe** [comment]
Hello @pandashashwat97, a GitHub walkthrough for this codelab is available here: https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app#4

If this does not resolve the issue, may you please provide the URL of the codelab where you experienced the issue? Thanks!
