### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by dreambo4** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#45]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app

**In which task and step of the codelab can this issue be found?**
at the beginning of step 2

**Describe the problem**
Miss a hyperlink on `Create and run your first Android app`

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app
2. Switch to Step 2
3. In the block of `Important`

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![圖片](https://user-images.githubusercontent.com/29445671/115371828-e6be6500-a1fc-11eb-9e33-961326e7f155.png)

**Comment by jtavva** [comment]
@dreambo4 
Thank you so much for reporting this issue. This is fixed and will be published soon.
