### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by SamShady0** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#48]
In section 4, in the "Modify a function to have two arguments" section, in the first paragraph, the text is highlighted in the code font while the code is in the normal text font.
![Screenshot 2021-04-23 140310](https://user-images.githubusercontent.com/71729129/115868392-a9e0b100-a43c-11eb-9675-6e0648c62587.png)

**Comment by osuleymanova** [comment]
@SamShady0 
Thank you for reaching out to us. The issue with the misplaced normal text and code fonts will be fixed and republished now.
