### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by chelingliao** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#50]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#0

**In which task and step of the codelab can this issue be found?**
In unit 1
 -> 2nd pathway (Create your first Android app)
 -> "Create and run your first Android app" lesson

**Describe the problem**
In this page the language selector on the navbar didn't work.

**Steps to reproduce?**
1. Go to...
"Create and run your first Android app" lesson
2. Click on...
Language selector on the navbar
3. See error...
It's didn't work

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@chelingliao 

Thank you for reaching out to us. The issue is fixed.
