### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by thtsoi8** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#51]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#2

**In which task and step of the codelab can this issue be found?**
Create and run your first Android app - step 3

**Describe the problem**
Unable to build the app.
Execution failed for task ':app:processDebugMainManifest'.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.2 RC1
_API version of the emulator:_ R

**Additional information**
After changed to use Android Gradle Plugin Version 4.0.2 and Gradle Version 6.4.1. The app can be built.

**Comment by ashnohe** [comment]
Happy to hear you resolved this issue!

In general, for best performance, use the latest possible version of both gradle and the plugin. For more information see [Update Gradle](https://developer.android.com/studio/releases/gradle-plugin).
