### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by ITReporter** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#52]
It seems that the printBorder function does not work. 

How to over come this problem?
![printBorder issue](https://user-images.githubusercontent.com/83600839/117077193-8f0d1700-ad2f-11eb-89cf-a98b6b7019fb.JPG)

**Comment by osuleymanova** [comment]
@ITReporter 
Thank you for reaching out to us.

Your code is almost correct but after fun main() {....} you missed to add 

```
fun printBorder() {
    println("=======================")
}
```


Your finished code should look like this:

```
fun main() {
    printBorder()
    println("Happy Birthday, Paolo!")
    printBorder()
}

fun printBorder() {
    println("=======================")
}
```
