### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by Frans122** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#54]
**URL of codelab**
codelab

**In which task and step of the codelab can this issue be found?**
starting a new project by: Creating your first app. 

**Describe the problem**
I get the following message:

Gradle sync failed: Could not find org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.0-release-764.
			Searched in the following locations:
			- https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.5.0-release-764/kotlin-gradle-plugin-1.5.0-release-764.pom
			- https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.5.0-release-764/kotlin-gradle-plugin-1.5.0-release-764.pom
			Required by:
			project : (7 s 823 ms)**

**Versions**
_Android Studio version:_ 4.2  
_API version of the emulator:_? 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/84081327/117979392-23c8d380-b333-11eb-8e96-3d0913ccd76a.png)

**Comment by ashnohe** [comment]
Hi @Frans122, can you try changing ext.kotlin_version to `'1.5.31'`?

Your build.gradle file should look like this: https://github.com/google-developer-training/android-basics-kotlin-birthday-card-app-solution/blob/master/build.gradle
