### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#56]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app#1

**In which task and step of the codelab can this issue be found?**
In the sentence: "Important: If you're not familiar with creating a new project in Android Studio, see Create and run your first Android app for details."

**Describe the problem**
It seems that the part "Create and run your first Android app" should provide a hyperlink, but it doesn't.

**Steps to reproduce?**
As stated above.

**Versions**
Not applicable.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@KKH-tw 
Thank you for reaching out to us. This issue will be fixed now.
