### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by PilarPinto** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#59]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
I can not run the project follow the instructions. I have problems with Gradle and the run is disabled. Even I try to re install the android studio but this does not work 

**Steps to reproduce?**
1. Go to...github and download
2. Click on...android studio and open the project
3. See error...No run button is able

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@PilarPinto 
Please provide us with the screenshots.

**Comment by ashnohe** [comment]
Closing this issue for now, but if you can provide screenshots that would be really helpful in troubleshooting this issue.

You might also try these steps:
1. Ensure your gradle files looks like this:
  - [app/build.gradle](https://github.com/google-developer-training/android-basics-kotlin-birthday-card-app-solution/blob/master/app/build.gradle)
  - [build.gradle](https://github.com/google-developer-training/android-basics-kotlin-birthday-card-app-solution/blob/master/build.gradle)
2. Sync your gradle files (File > Sync Project with Gradle Files).
3. Build your project.
