### ISSUE TITLE
Android Basics: Text in code font - kotlin-birthday-message

### ISSUE THREAD

**Issue by melisatanrikulu** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#6]
![Ekran görüntüsü 2020-12-03 113404](https://user-images.githubusercontent.com/61549443/100984218-7cfa3300-355b-11eb-8f94-5e44b9e88068.png)
In section "Print a birthday banner with a border" and just under the title "Modify a function to have two arguments", the text is stylized in the wrong way. I believe this is because of the quotation mark right after printBorder() in the third line.

**Comment by jtavva** [comment]
@melisatanrikulu 
Thank you so much for reporting this issue. This is fixed and will be published soon.
Codelab URL: 
https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#3
