### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by vamendez00** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#61]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app#4

**In which task and step of the codelab can this issue be found?**
Step 5
Was able to create the birthday app and view it on emulator. After downloading the master solution, i keep getting this. I've tried invalidating cache and restarting. I've also deleted the project and re-downloaded the zip file, unpacked it, but it just wont sync.

**Describe the problem**
Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-6.5-all.zip

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment]
@vamendez00 
Thanks for reporting this issue. The solution file has recently been updated to run with the latest version of Android Studio. If you're still experiencing this issue, you might try to download the latest solution. Thanks!
