### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by Mohit-011** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#63]
In the 5th section, Create printCakeCandles() part, the step in which one were to pass a "print("")" command for insetting the flame of the candles has been missed out. 
https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#:~:text=Create%20printCakeCandles()

**Comment by osuleymanova** [comment]
@Mohit-011 
Thank you so much for reporting this issue. This is fixed and will be published soon.
