### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by pgorecka** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#65]
**https://developer.android.com/courses/pathways/android-basics-kotlin-two**

**In all steps**

**System doesn't remember my progress. I have done some of the codelabs 3 times to see it 100% complete, yet after few days, some of the labs seem untouched.

Win10 Home 64. Chrome latest version**

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@pgorecka 
Are you singed in when you take this codelabs?

**Comment by pgorecka** [comment]
Yes, I'm signed in. Also when I refresh the site with codelabs, it takes a while befeore any progress (green check mark) is seen. It's not my internet connection for sure. I dont experience any lags. ---- On Cz, 24 cze 2021 23:00:24 +0200  ***@***.***  wrote ----
@pgorecka
Are you singed in when you take this codelabs?

**Comment by jtavva** [comment]
@pgorecka 
Can you please send us some screenshots after you finish some codelabs?

**Comment by ashnohe** [comment]
Closing this issue for now, but let us know if you're still seeing this issue and if you can provide some screenshots. Thanks!
