### ISSUE TITLE
Android Basics: kotlin-birthday-message help to resolve this issue

### ISSUE THREAD

**Issue by Kushagra-NOVA175** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#68]
Create a cake with the layers and candles.I tried to print birthday with age and cake but it showing wrong.
 ,,,,,,,,,,,,,,,,,,,,,,,,
 ||||||||||||||||||||||||
==========================
@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@
my codes are
fun main() {
    val age = 24
    val layer = 5
    printCakeCandles(age)
    printCakeTop(age)
    printCakeBottom(age,layer)
}
fun printCakeTop(age: Int)
{
    repeat(age+2)
    {
        print("=")
    }
    println()
}
fun printCakeCandles(age: Int)
{
    print(" ")
    repeat(age)
    {
        print(",")
    }
    println()
    
    print(" ")
    {
        print("|")
    }
    println()
}
fun printCakeBottom(age: Int, layer: Int)
{
    repeat(age+2)
    {
        print("@")
    }
    println()
}
the outputs are:-
 ,,,,,,,,,,,,,,,,,,,,,,,,Function0<kotlin.Unit>

==========================
@@@@@@@@@@@@@@@@@@@@@@@@@@

**Comment by jtavva** [comment]
@Kushagra-NOVA175 
Thank you for reaching out to us.

Your code is almost correct but you missed to add `repeat (age)`, `repeat (layers)` and a closing brace. 

![image](https://user-images.githubusercontent.com/24260141/126244265-69348b7c-484b-4aa0-82f5-0292dce79301.png)

Completed and corrected code:
https://pl.kotl.in/VNKiAiAb_

Output: 
![image](https://user-images.githubusercontent.com/24260141/126244399-1d64bf1c-4df0-4dd2-bb7c-8f0fa8b4b7a2.png)
