### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by genocon** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#7]
In Step 4, the Repeat a Border section, you refer to the printBorder() FUNCTION as a METHOD. The term METHOD was not previously mentioned in the step . I know it's the same thing, but it could be confusing to people new to programming.

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. We changed it to function. This is fixed and will be published soon.
