### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by traywolf** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#72]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app#1

**In which task and step of the codelab can this issue be found?**
Step 3:  "Expand the 'app' folder, then the 'res' Folder, then the 'layout' folder.
           (looking for file "activity_main.xml")

**Describe the problem**
Step 3 path should be "Expand the 'app' folder, the 'src', the 'main', then the 'layout' folder

I am new to this, and I could be wrong, but this file was no-where near where the tutorial suggested.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.2.2
_API version of the emulator:_ unclear or n/a

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@traywolf 
Thank you for reaching out to us.

In your Android Studio, in the project pane, make sure you are in the Android view not in Project view. Once you select the **Android** view, you will find the `activity_main.xml` file in the path mentioned in the codelab.


![image](https://user-images.githubusercontent.com/24260141/126830582-ae0a9553-30fc-4bee-a4ce-c8793288e841.png)
