### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by SueNaEunYang** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#88]
<img width="756" alt="스크린샷 2021-08-19 오후 11 11 17" src="https://user-images.githubusercontent.com/29892794/130083725-4fdafec5-6626-49df-8223-ae43158832c7.png">

Hi, I'm an android beginner and while I was reading this very beginning part, I found out the untranslated part. It seems like it was thought to be a part of the code line, but actually needs to be translated. I recommend as following :

from "
You would not repeat this pattern 23 times as it would be way too long. You could repeat it maybe 4 times. To accomplish this, you could change the number of repetitions in the repeat()statement ofprintBorder()`.
"

to "
이 패턴을 23번 반복하는 것은 너무 길기 때문에 그렇게 하지 않고 4번 정도만 반복하면 될 것 같습니다. 그러기 위해서, `repeat()`문에서 `printBorder()`의 반복 횟수를 변경할 수 있습니다.
"

I would like someone to review this translation and update this part if possible :)

with @peebbv6364

**Comment by ashnohe** [comment]
Hi @SueNaEunYang this portion of the codelab was updated. Can you confirm if the translation issue still exists? Thank you!

URL for context: https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message#4

**Comment by SueNaEunYang** [comment]
Hi @ashnohe , thank you for your carings! I noticed that the problem above just moved to the prior page : https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message#3
and it still needs to be fixed at the same part. Could this then be fixed? :)

<img width="817" alt="스크린샷 2021-11-03 오전 10 38 11" src="https://user-images.githubusercontent.com/29892794/139999994-f6889576-1285-4751-a009-e787e30dbbc6.png">

(This seems to be occuring because the code lab wants to use " ` " this mark as a part of the pretty boarder image but the computer accepts it as a start and end signs of a code line, mistakenly making the following explanations not a part to be translated)

Related #95 , #96
