### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by chaibee** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#89]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#2

**In which task and step of the codelab can this issue be found?**
I was trying to download and install emulator

**Describe the problem**
There is a message that said "no emulator installed"
![No emulator](https://user-images.githubusercontent.com/89629156/131083926-cd0dd164-3b2e-4e68-a917-f11e298b6412.JPG)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Android Studio Artic Fox, 2020.3.1. patch 1
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment]
Hi @chaibee, thanks for reaching out. If you're still experiencing this issue, may you try to install the emulator either by clicking on the "Install Emulator" link or by following the instructions as described in this [guide](https://developer.android.com/studio/run/emulator#install)?
