### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by giedriusMarcinkonis** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#9]
Whenever i try to print, either cake top, bottom or candles - I receive an note, that says "age is never used".
Even when i just copy code from training course

**Comment by jtavva** [comment]
@giedriusMarcinkonis 
Thank you for reaching out to us.
Here is a screenshot of the output, it is working as expected.
If you still encounter problems, please copy and paste your problematic code here so we can troubleshoot further. 
![image](https://user-images.githubusercontent.com/24260141/102809449-dc877980-4376-11eb-9b30-88eb422d3b2f.png)
