### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by sharaijaz** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#91]
https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#3

Use arguments to change the border

fun printBorder(border: String) {
    repeat(23) {
        print("=") **(at this place string border to be called otherwise = will be printed for border)**
    }
    println()
}

**Comment by sharaijaz** [comment]
![image](https://user-images.githubusercontent.com/40498691/131645791-fe869cae-5e3e-4c69-8109-e123c7c9ae55.png)

**Comment by ashnohe** [comment]
Hi @sharaijaz, thanks for reaching out and nice catch. This is working as intended, step 9 offers an explanation and step 10 uses the `border` parameter as you called out.

> 9. Hover the mouse over the exclamation mark, and a message appears. It says "Parameter 'border' is never used." This warning explains the problem with the output. You are passing a new string for the border to the function, but you are not using it for printing.
> 10. Change the printBorder() function to use the passed in border instead of printing the "=". This works exactly the same as if border was a variable that you defined inside the function!
