### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by Gadiguibou** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#92]
The following sentence appears at the top of page 4:

> Great job! You printed one line of text using the `println() function`.

I think it should be formatted the following way instead.

> Great job! You printed one line of text using the `println()` function.

Hope this helps!

**Comment by ashnohe** [comment]
url: https://developer.android.com/codelabs/basic-android-kotlin-training-first-kotlin-program#3
