### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by svtdoug** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#93]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app#3

**In which task and step of the codelab can this issue be found?**
#4.

**Describe the problem**
It starts talking about textAppearance, but the example shows textSize..  Inconsistent.  Also, textSize is not in Common Attributes, which is strange.  

**Steps to reproduce?**
1. Go to... URL, step 4, read.  

Android Studio Arctic Fox 2020.3.1 Patch 2.

**Comment by ashnohe** [comment]
Thank you @svtdoug for reporting this issue. TextSize is contained within TextAttributes, as explained in step 5. 

I'm marking this as a documentation issue. I feel the image showing TextSize should come as a new line (rather than in-line) below step 5.

**Comment by osuleymanova** [comment]
@svtdoug 
Thank you for reaching out to us. Please refer to the image below:

![Screen Shot 2022-08-02 at 3 18 40 PM](https://user-images.githubusercontent.com/86437155/182483649-ecdc9eb3-69f9-4b1d-a809-9cf60b0c21fa.png)

As for your concerns, we added a minor clarification to the step 5 and the image below it. Common Attributes include textSize attribute.
