### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by johnshea** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#94]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app#2

**In which task and step of the codelab can this issue be found?**
"Position the TextView" Step 3

**Describe the problem**
Typo at the end of the sentence. It has "ConstrainLayout" (missing the "t" on Constraint) when it should be "ConstraintLayout".

**Steps to reproduce?**
N/A

**Versions**
N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="400" alt="Screen Shot 2021-09-16 at 10 10 13 AM" src="https://user-images.githubusercontent.com/7107817/133627613-b4330d7f-90ee-4013-8068-8b8528d34704.png">

**Comment by osuleymanova** [comment]
@johnshea 
Hi John, thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-08-26 at 11 59 17 AM](https://user-images.githubusercontent.com/86437155/186973749-b9535195-e7fe-4ea2-a3e0-e1f9102de34f.png)
