### ISSUE TITLE
Android Basics: kotlin-birthday-message, JP Translation bug

### ISSUE THREAD

**Issue by inucat** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#95]
Hello I've just started the course and found the translation bug for Japanese text.

**Where the bug was found**

https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message

The passage in Step 4 "関数を変更して 2 つの引数を指定する":

```
1 文字を超える別のパターンを使用する場合は、"-._,-'". You would not repeat this pattern 23 times as it would be way too long. You could repeat it maybe 4 times. To accomplish this, you could change the number of repetitions in the repeat()statement ofprintBorder()` と指定します。このパターンは長すぎるため、23 回繰り返す必要はありません。4 回程度繰り返せばよいでしょう。printBorder() の repeat() ステートメントの繰り返し回数を変更することで、回数の調整が可能です。ただし、他にもっと良い方法があります。
```

**Expected behavior**

The sentence

```
"-._,-'". You would not repeat this pattern 23 times as it would be way too long. You could repeat it maybe 4 times. To accomplish this, you could change the number of repetitions in the repeat()statement ofprintBorder()`
```

should be like:

```
`-._,-'
```

**Possible reason**

The Backquote symbol looks not properly escaped.

**Possibly related issue:** 

#88

**Browser Environment**

Windows 10 20H2 (19042.123)

Microsoft Edge v93.0.961.47 (x86_64), with all Extensions turned off

![screenshot](https://user-images.githubusercontent.com/70513648/133785968-a9c661dd-0b9c-4ead-ab4f-4cd073f67319.png)

Thank you.

**Comment by ashnohe** [comment]
Thank you @inucat for reporting this issue. The formatting has been adjusted on this page: https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message#3

However, it has not carried over to other languages. I'll mark this as a formatting issue.
