### ISSUE TITLE
Android Basics: birthday-card-app

### ISSUE THREAD

**Issue by Dayush82** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#97]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app#1
**In which task and step of the codelab can this issue be found?**
Change the Hello World message

**Describe the problem**
When I change Hello World to Happy Birthday! keep getting an  hardcoded text error message

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment]
Thank you @Dayush82 for reaching out. If you are still experiencing this issue, may you please provide the exact error message? Thanks!

If it helps, step 12 states:
> Change it to say Happy Birthday!, then press the Enter key. **If you see a warning about a hardcoded string, don't worry about it for now. You will learn how to get rid of that warning in the next codelab.**
