### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by michaelssim** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#99]
https://developer.android.com/codelabs/basic-android-kotlin-training-first-kotlin-program?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-kotlin-program#1

In the last paragraph regarding compilation, there's a sentence that can be improved.

Before:
"If there are problems, they will appear in pane at the bottom."

After:
"If there are problems, they will appear in **the** pane at the bottom."

Since error indicators also show up on the left sidebar next to the code, I think it's worth mentioning that as well. 

For example, I would elaborate further and write something like: 

"If there are problems, they will appear in the pane at the bottom as well as the shaded sidebar next to the code. For example, deleting the quotation mark at the end of the message generates several error indicators and messages. For simple syntax mistakes, the code tool even shows a red underline pointing to the exact location where the problem occurred. Neat!"

![kotlin-playground-helpful-error-indicators-example](https://user-images.githubusercontent.com/81500505/135169696-380159fd-9853-4343-8583-59998db698f0.png)

**Comment by osuleymanova** [comment]
@michaelssim 
Thank you for reaching out to us. The typo is fixed:

![Screen Shot 2022-08-02 at 2 47 21 PM](https://user-images.githubusercontent.com/86437155/182479419-d409415f-d81a-4b79-9c79-ec23741afb2a.png)

 As for your suggestion to edit the text, no changes to the codelab content are required.
